# Site settings
title: downey.io
name: Tim Downey
description: "Serendipitous photography blog"
keywords:
  - photography
  - photoblog
baseurl: ""
url: "http://photo.downey.io"

# Build settings
highlighter: pygments
paginate: 5
permalink: photos/:year/:month/:day/:title.html

exclude:
  - s3_website.yml
gems:
  - jekyll-sitemap

assets:
  sources:
    - '../assets/javascripts'
    - _assets/javascripts
    - _assets/stylesheets
