# Site settings
title: downey.io
name: Tim Downey
description: "just another blog"
keywords:
  - programming
  - tim downey
  - programming blog
  - ruby
  - rails
baseurl: ""
url: "http://downey.io"

# Build settings
highlighter: rouge
paginate: 5
paginate_path: "blog/page:num"
permalink: "blog/:title"

exclude:
  - s3_website.yml
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

assets:
  sources:
    - '../assets/javascripts'
    - _assets/javascripts
    - _assets/stylesheets
