# Site settings
title: downey.io
name: Tim Downey
description: "Software development blog and online home of Tim Downey."
keywords:
  - tim downey software engineer
  - tim downey
  - programming blog
  - ruby
  - software development
baseurl: ""
url: "http://downey.io"

# Build settings
highlighter: rouge
paginate: 5
paginate_path: "blog/page:num"
permalink: "blog/:title/"

exclude:
  - s3_website.yml
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
