# Site settings
title: downey.io
name: Tim Downey
description: "Tim's really good programming blog."
baseurl: ""
url: "http://downey.io"

# Build settings
highlighter: pygments
paginate: 5
paginate_path: "blog/page:num"
permalink: "posts/:year/:month/:day/:title.html"

exclude:
  - s3_website.yml
gems:
  - jekyll-sitemap

assets:
  sources:
    - '../assets/javascripts'
    - _assets/javascripts
    - _assets/stylesheets
